# Wandb Configuration

entity : "team"
project : "hogehoge"
name : "testjob"

# Model Configuration

n_dims : 64
n_heads : 16
n_layers : 27
intermediate_size : 2048

# Training Configuration

sample_size : 2000
# gradient_accumulation_steps: 256
# logging_steps: 2
# num_train_epochs: 3
# save_total_limit: 5
# overwrite_output_dir: True



